"""fix device model

Revision ID: 54f95ca6be0c
Revises: d67344a9c3bb
Create Date: 2024-11-20 16:02:11.493647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f95ca6be0c'
down_revision: Union[str, None] = 'd67344a9c3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_seen', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_seen')
    # ### end Alembic commands ###
