"""mudando logica de negocio 2

Revision ID: 60824e30c0e6
Revises: 7415f82ed4ef
Create Date: 2024-11-18 22:09:16.153731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60824e30c0e6'
down_revision: Union[str, None] = '7415f82ed4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'description')
    op.add_column('users', sa.Column('community_id', sa.Integer(), nullable=False))
    op.drop_column('users', 'community')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('community', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'community_id')
    op.add_column('communities', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
