"""changing device properties

Revision ID: 9a3233f5f49a
Revises: 54f95ca6be0c
Create Date: 2024-11-20 16:50:59.109992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3233f5f49a'
down_revision: Union[str, None] = '54f95ca6be0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('connected', sa.Boolean(), nullable=True))
    op.drop_column('devices', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'connected')
    # ### end Alembic commands ###
