"""devicedata

Revision ID: d3d15f7b1fe1
Revises: 9f95120163d4
Create Date: 2024-11-20 17:43:43.879207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d15f7b1fe1'
down_revision: Union[str, None] = '9f95120163d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_data', sa.Column('corrente', sa.String(), nullable=False))
    op.add_column('device_data', sa.Column('tensao', sa.String(), nullable=False))
    op.drop_column('device_data', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_data', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('device_data', 'tensao')
    op.drop_column('device_data', 'corrente')
    # ### end Alembic commands ###
